#!/bin/bash

# nsfu
cd "$(dirname "$0")"
if [ -f ".env" ]; then
  export $(grep -v '^#' .env | xargs -d '\n')
fi

set -x

export CGO_ENABLED=1

if [[ $(uname -a | grep -io msys) ]]; then
  WIN="1"
  # windows
  export CGO_CFLAGS='-I/mingw64/include/taglib/'
  export CGO_LDFLAGS='-L/mingw64/lib/ -ltag_c.dll -ltag.dll -lstdc++ -lm -lz'
fi

if [ "$1" = "run" ]; then
  go run cmd/cli/tag.go

elif [ "$1" = "play" ]; then
  go run cmd/play/play.go

elif [ "$1" = "taglib" ]; then
  if [[ $WIN ]]; then
    echo "https://github.com/taglib/taglib/blob/master/INSTALL.md#windows"
    exit 1
  fi

  cd taglib && \
  cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_BINDINGS=ON . && \
  make && sudo make install
  if [ "$?" != "0" ]; then
    echo "Make sure to install whatever cmake asks you to"
    exit 1
  fi

  

elif [ "$1" = "build" ]; then
  mkdir -p build
  go build  -o build/ cmd/cli/tag.go

  if [[ $WIN ]]; then
    if [[ $? -eq 0 ]]; then
      cp $(ldd build/tag.exe | grep -vi 'system32' | cut -d' ' -f3) build/
    fi
  fi

elif [ "$1" = "test" ]; then
  go test -v ${@:2}

elif [ "$1" = "clean" ]; then
  go clean -cache
  rm -rf build/
else
  set +x
  echo "Shiver me timbers!!.. Invalid arrghh - ${@:1}"
  exit 1
fi
